### PR TITLE
Fixes OpenDataFormats/worldcities#2

### PR DESCRIPTION
**Pull request by davidarvan**

### CODE REVIEW

**Comment by andreialecu** [comment]
Hey! So I was looking at the changes here, and maybe there's a way to not hardcode this?

I noticed that the lines for the Sectors look like this in the data file:

```
11048317	Sector 1	Sector 1	Sectorul 1	44.49239	26.04831	P	PPLX	RO		10	179132	11055041		225453		86	Europe/Bucharest	2017-11-24
11048318	Sector 2	Sector 2	Sectorul 2	44.4528	26.13321	P	PPLX	RO		10	179132	11055040		345370		80	Europe/Bucharest	2017-11-24
11048319	Sector 3	Sector 3	Sectorul 3	44.4234	26.16874	P	PPLX	RO		10	179132	11055044		385439		76	Europe/Bucharest	2017-11-24
11048320	Sector 4	Sector 4	Sectorul 4	44.37571	26.12085	P	PPLX	RO		10	179132	11055042		287828		79	Europe/Bucharest	2017-11-24
11048322	Sector 5	Sector 5	Sectorul 5	44.38808	26.07144	P	PPLX	RO		10	179132	11055043		271575		81	Europe/Bucharest	2017-11-24
11048323	Sector 6	Sector 6	Sectorul 6	44.43579	26.01649	P	PPLX	RO		10	179132	11055039		367760		95	Europe/Bucharest	2017-11-24
```

PPLX is "section of populated place" according to: http://www.geonames.org/export/codes.html 

There are many lines marked with PPLX in the file, so I assume they would have the same issue.

It's odd that there is also a separate line for Bucharest:

```
683506	Bucharest	Bucharest	BUH,Boekarest,Boukouresti,Bucarest,Bucaresta,Bucareste,Bucarèst,Bucharest,Bucuresti,Bucureşti,București,Buekres,Bukarest,Bukarestas,Bukareste,Bukaresto,Bukareszt,Bukareŝto,Bukareštas,Bukharest,Bukureshh,Bukuresht,Bukureshta,Bukureshti,Bukurest,Bukurešt,Bukurešť,Buxarest,Búkarest,Bûkarest,Bükreş,bkharst,bu jia lei si te,bukaresuto,bukulesyuti,bwkharst,bwqrst,Βουκουρέστι,Букурешт,Букурещ,Бухарест,Բուխարեստ,בוקאַרעשט,בוקרשט,بخارست,بوخارست,بۇخارېست,པུ་ཁ་རེ་སིད,ბუქარესტი,ቡካረስት,ブカレスト,布加勒斯特,부쿠레슈티	44.43225	26.10626	P	PPLC	RO		10	179132	11055044		1877155		83	Europe/Bucharest	2016-02-07
```

http://download.geonames.org/export/dump/admin1CodesASCII.txt has:

`RO.10	Bucureşti	Bucuresti	683504`

and http://download.geonames.org/export/dump/admin2Codes.txt has:

`RO.10.179132	Municipiul Bucureşti	Municipiul Bucuresti	8335003`

They are both names (in Romanian) for the city.

Perhaps it might be a better idea to correlate these somehow?

**Comment by andreialecu** [comment]
As an example, there's this line:

```
3427387	Villa Ortúzar	Villa Ortuzar	Villa Ortuzar,Villa Ortúzar	-34.57973	-58.46829	P	PPLX	AR		07	02015			22500		26	America/Argentina/Buenos_Aires	2017-05-08
```

https://en.wikipedia.org/wiki/Villa_Ort%C3%BAzar

Seems to be just a neighborhood. So all PPLX should be handled differently.

**Comment by andreialecu** [comment]
As a probably easier fix, I think simply excluding all `PPLX` from being considered cities would do it. For Bucharest there is already a distinct line for `Bucharest`. 

And Buenos Aires also has its own line:
```
3435910	Buenos Aires	Buenos Aires	BUE,Baires,Bonaero,Bonaeropolis,Bonaëropolis,Bos Aires,Bouenos Aires,Bouonezar,Bouonézâr,Buehnas-Ajrehs,Buehnos Ajres,Buehnos-Ajres,Buehnos-Ajres osh,Buenos Aires,Buenos Airės,Buenos Ajres,Buenos Ayres,Buenos-Aires,Buenos-Ajres,Buenos-Ayres,Buenos-Aýres,Buenosairesa,Buénos Ayrés,Bwenoze,Bwènozè,Búenos Aíres,Ciudad Autonoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Ciudad de La Santisima Trinidad y Puerto de Santa Maria del Buen Ayre,Ciudad de La Santísima Trinidad y Puerto de Santa María del Buen Ayre,Lungsod ng Buenos Aires,Santa Maria del Buen Ayre,Santa María del Buen Ayre,bawnosxires,bu yi nuo si ai li si,bu'enosa a'iresa,buenos-airesi,buenosaires,buenoseuaileseu,buenosuairesu,buraenosa a'iresa,buyenosa a'iresa,bwyns ayrs,bwynws ayrs,bwynws ayrys,byu'enosa erisa,byunas airis,byunas ayels,bywns ayrs,puvenas airis,Μπουένος ΄Aιρες,Μπουένος Άιρες,Буенос Аирес,Буенос Айрес,Буенос Аірес,Буенос Ајрес,Буенос-Аирес,Буенос-Айрес,Буэнас-Айрэс,Буэнос Айрес,Буэнос-Айрес,Буэнос-Айрес ош,Բուենոս Այրես,בואנוס איירס,בוענאס איירעס,بوئنوس آیرس,بوينس آيرس,بوينوس ايريس,بۆینس ئایرس,بیونس آئرس,बुएनोस आइरेस,ब्युएनॉस एरीस,বুয়েনোস আইরেস,বুৱেনোস আইরেস,புவெனஸ் ஐரிஸ்,ಬ್ಯೂನಸ್ ಐರಿಸ್,ബ്യൂണസ് അയേഴ്സ്,บัวโนสไอเรส,པུ་ཨེ་ནོ་སི་ཨས་རི་སི།,ဗျူနိုအေးရိစ်မြို့,ბუენოს-აირესი,ብዌኖስ አይሬስ,ブエノスアイレス,布宜諾斯艾利斯,布宜诺斯艾利斯,부에노스아이레스	-34.61315	-58.37723	P	PPLC	AR		07				13076300		31	America/Argentina/Buenos_Aires	2019-09-05
```

So the nearest large city should still be the proper one if PPLX is excluded.

Getting district information could be a separate call such as `getNearestNeighborhood` perhaps, but it could come later down the road.

**Comment by davidarvan** [comment]
Oh great find! Looks like there are 966 PPLX entries in the dataset. Since
there are also rows for the city proper, just filtering them out does make
sense for now.

I'll make the change and update the pull request.

**Pull request merged**
